import { defineConfig } from 'vitest/config';
import path from 'node:path';

const resolve = (pkg: string) =>
  path.resolve(__dirname, `packages/${pkg}/src/index.ts`);

export default defineConfig({
  resolve: {
    alias: {
      '@acds/core-types': resolve('core-types'),
      '@acds/security': resolve('security'),
      '@acds/audit-ledger': resolve('audit-ledger'),
      '@acds/provider-adapters': resolve('provider-adapters'),
      '@acds/provider-broker': resolve('provider-broker'),
      '@acds/policy-engine': resolve('policy-engine'),
      '@acds/routing-engine': resolve('routing-engine'),
      '@acds/execution-orchestrator': resolve('execution-orchestrator'),
      '@acds/sdk': resolve('sdk'),
      '@acds/evaluation': resolve('evaluation'),
      '@acds/adaptive-optimizer': resolve('adaptive-optimizer'),
      '@acds/shared-utils': resolve('shared-utils'),
      '@acds/persistence-pg': resolve('persistence-pg'),
      '@acds/grits': resolve('grits'),
      '@acds/sovereign-runtime': resolve('sovereign-runtime'),
      '@acds/observability': resolve('observability'),
    },
  },
  test: {
    passWithNoTests: true,
    include: [
      'packages/*/src/**/*.test.ts',
      'packages/sovereign-runtime/tests/**/*.test.ts',
      'apps/*/src/**/*.test.ts',
      'tests/**/*.test.ts',
    ],
    coverage: {
      provider: 'v8',
      include: [
        'packages/*/src/**/*.ts',
        'apps/grits-worker/src/checkers/**/*.ts',
        'apps/api/src/**/*.ts',
      ],
      exclude: [
        '**/*.test.ts',
        '**/__test-support__/**',
        '**/index.ts',
        '**/types.ts',
        '**/enums/**',
        '**/entities/**',
        '**/*.d.ts',
        '**/dist/**',
        '**/main.ts',
        'packages/sdk/**',
        'packages/core-types/**',
        'packages/observability/**',
        'packages/shared-utils/**',
        'packages/grits/src/types/**',
        'packages/grits/src/repositories/**',
        'packages/grits/src/checker/IntegrityChecker.ts',
        'packages/adaptive-optimizer/src/adaptation/AdaptationApprovalRepository.ts',
        'packages/adaptive-optimizer/src/adaptation/AdaptationApprovalState.ts',
        'packages/adaptive-optimizer/src/adaptation/AdaptationLedgerWriter.ts',
        'packages/adaptive-optimizer/src/adaptation/AdaptationRollbackRecord.ts',
        'packages/adaptive-optimizer/src/adaptation/AutoApplyDecisionRecord.ts',
        'packages/adaptive-optimizer/src/adaptation/RankingSnapshot.ts',
        'packages/adaptive-optimizer/src/adaptation/EscalationTuningState.ts',
        'packages/adaptive-optimizer/src/global/BudgetAllocationState.ts',
        'packages/adaptive-optimizer/src/global/FamilyValueScore.ts',
        'packages/adaptive-optimizer/src/plateau/PlateauSignal.ts',
        'packages/adaptive-optimizer/src/state/CandidatePerformanceState.ts',
        'packages/adaptive-optimizer/src/state/FamilySelectionState.ts',
        'packages/adaptive-optimizer/src/state/OptimizerStateRepository.ts',
        'packages/adaptive-optimizer/src/guidance/StrategyRecommendation.ts',
        'packages/provider-adapters/src/base/AdapterTypes.ts',
        'packages/provider-adapters/src/base/ProviderAdapter.ts',
        'packages/provider-adapters/src/**/*Config.ts',
        'packages/provider-broker/src/health/ProviderHealthRepository.ts',
        'packages/provider-broker/src/registry/ProviderRepository.ts',
        'packages/provider-broker/src/lease/ExecutionLease.ts',
        'packages/policy-engine/src/application/**',
        'packages/policy-engine/src/global/**',
        'packages/policy-engine/src/process/**',
        'packages/policy-engine/src/services/PolicyRepository.ts',
        'packages/audit-ledger/src/formatters/AuditEvent.ts',
        'packages/audit-ledger/src/writers/AuditEventWriter.ts',
        'packages/security/src/crypto/SecretCipherStore.ts',
        'packages/evaluation/src/staged/StagedAdaptationDecision.ts',
        'packages/evaluation/src/staged/StagedExecutionPlan.ts',
        'packages/execution-orchestrator/src/staged/StagedEscalationDecision.ts',
        'packages/execution-orchestrator/src/staged/StagedExecutionPlan.ts',
        'packages/security/src/secrets/SecretCipherStore.ts',
        'apps/api/src/types/**',
        'apps/api/src/routes/**',
        'apps/api/src/config/appConfig.ts',
        'apps/api/src/bootstrap/createDiContainer.ts',
        'apps/api/src/bootstrap/registerMiddleware.ts',
        'apps/api/src/app.ts',
        // Sovereign runtime type-only files (pure interfaces/types, no runtime code)
        'packages/sovereign-runtime/src/domain/source-types.ts',
        'packages/sovereign-runtime/src/domain/provider.ts',
        'packages/sovereign-runtime/src/domain/capability.ts',
        'packages/sovereign-runtime/src/domain/session.ts',
        'packages/sovereign-runtime/src/domain/method-registry.ts',
        'packages/sovereign-runtime/src/domain/execution-request.ts',
        'packages/sovereign-runtime/src/domain/execution-response.ts',
        'packages/sovereign-runtime/src/providers/provider-runtime.ts',
        'packages/sovereign-runtime/src/providers/apple/apple-interfaces.ts',
        'packages/sovereign-runtime/src/registry/registry-types.ts',
        'packages/sovereign-runtime/src/grits/validation-types.ts',
        'packages/sovereign-runtime/src/telemetry/event-types.ts',
        'packages/sovereign-runtime/src/telemetry/audit-logger.ts',
      ],
      reporter: ['text', 'text-summary', 'json'],
    },
  },
});
